### ISSUE TITLE
Possible issue with Xcode 8 beta and Xcode 8 GM

### ISSUE THREAD

**Issue by mokagio** [schwa/punic#9] opened 2016-09-13 10:11 UTC
`punic build` is failing for me when using the toolchain from Xcode 8 beta 6 and Xcode 8 GM.

```
$ xcode-toggle -l                                                                      8:06pm
/Applications/Xcode-7.app
/Applications/Xcode-beta.app
/Applications/Xcode.app [Current]
$ punic build                                                                          8:06pm
Traceback (most recent call last):
  File "/usr/local/bin/punic", line 9, in <module>
    load_entry_point('punic==0.1.15', 'console_scripts', 'punic')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/punic/__init__.py", line 10, in <module>
    from .checkout import Checkout
  File "/usr/local/lib/python2.7/site-packages/punic/checkout.py", line 5, in <module>
    from punic.config import config
  File "/usr/local/lib/python2.7/site-packages/punic/config.py", line 117, in <module>
    config = Config()
  File "/usr/local/lib/python2.7/site-packages/punic/config.py", line 40, in __init__
    self.xcode = Xcode.default()
  File "/usr/local/lib/python2.7/site-packages/punic/xcode.py", line 22, in default
    Xcode.find_all()
  File "/usr/local/lib/python2.7/site-packages/punic/xcode.py", line 40, in find_all
    Xcode._default_xcode = [xcode for version, xcode in Xcode._all_xcodes.items() if xcode.developer_dir_path == default_developer_dir_path][0]
IndexError: list index out of range
```

Same issue selecting `/Application/Xcode-beta.app`.

[Link to the failing line in the source code](https://github.com/schwa/punic/blob/758c28d95626c1dad6804ce77c8b8c04d951c7e6/punic/xcode.py#L40)

**Comment by Palleas** [comment] 2016-09-14 00:48
Same issue for me, it's definitely linked to Xcode 8/GM because it works when I run the following:
`DEVELOPER_DIR=/Applications/Xcode-old.app punic build`

**Comment by schwa** [comment] 2016-09-14 18:48
So… "works for me" :-)

I'm probably unable to debug without more information... Can you reproduce this with something I can repro?

**Comment by Palleas** [comment] 2016-09-14 19:55
I've cleaned my laptop and I only have one Xcode installation now and it seems to be working. This is the installations I had: 

* Xcode-GM.app
* Xcode.app
* Xcode-beta.app

Let me know if I can provide more infos!

**Comment by schwa** [comment] 2016-09-16 17:27
" it seems to be working" and I can't reproduce.

So I'm closing this for now. If you see more problems please re-open!

**Closed by schwa** 2016-09-16 17:27 UTC
